platform :ios, '8.0'

#use_frameworks!
#use_modular_headers!

target 'OCHooking_Example' do
  pod 'OCHooking', :path => '../'
  
  target 'OCHooking_Tests' do
    inherit! :search_paths

    
  end
end
