# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
cache: cocoapods
podfile: Example/Podfile
before_install:
- gem install cocoapods --no-rdoc --no-ri --no-document --quiet
- gem install xcpretty --no-rdoc --no-ri --no-document --quiet
- pod install --project-directory=Example
script:
- xcodebuild test -workspace Example/OCHooking.xcworkspace -scheme 'OCHooking-Example' -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone XS' -configuration Debug | xcpretty -c
- pod lib lint --allow-warnings